# This is a basic workflow to help you get started with Actions

name: Bintray Publish

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  release:
    types:
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle clean
        run: ./gradlew clean
      - name: Gradle build
        run: ./gradlew build # if test's failed, don't publish
      - name: Check keys
        run: ./gradlew :kotlin-jvm-blocking-bridge:ensureBintrayAvailable :kotlin-jvm-blocking-bridge-compiler:ensureBintrayAvailable :kotlin-jvm-blocking-bridge-ide:ensureBintrayAvailable  -Dbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_user=${{ secrets.BINTRAY_USER }} -Dbintray_key=${{ secrets.BINTRAY_KEY }} -Pbintray_key=${{ secrets.BINTRAY_KEY }}
      - name: Gradle :mirai-console:bintrayUpload
        run: ./gradlew :kotlin-jvm-blocking-bridge:bintrayUpload :kotlin-jvm-blocking-bridge-compiler:bintrayUpload :kotlin-jvm-blocking-bridge-ide:bintrayUpload -Dbintray_user=${{ secrets.BINTRAY_USER }} -Pbintray_user=${{ secrets.BINTRAY_USER }} -Dbintray_key=${{ secrets.BINTRAY_KEY }} -Pbintray_key=${{ secrets.BINTRAY_KEY }}

