name: Gradle CI

on: [push, pull_request]

jobs:
  check_duplicate_workflows:
    name: Check for duplicate workflows
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          skip_after_successful_duplicate: 'true'
          concurrent_skipping: 'same_content'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
          paths_ignore: '["**/*.md"]'

  build:

    runs-on: ${{ matrix.platform }}
    needs: [ check_duplicate_workflows ]
    if: ${{ needs.check_duplicate_workflows.outputs.should_skip != 'true' }}
    strategy:
      matrix:
        java: [ '8', '11', '15' ]
        platform: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Cache Gradle packages
        uses: actions/cache@v2.1.5
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle

      - run: chmod +x gradlew
      - run: ./gradlew clean --scan
      - run: ./gradlew assemble --scan
      - run: ./gradlew build --scan