name: Gradle CI

on: [push, pull_request]

jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --scan

  build-on-macos:
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.1'
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --scan
