name: Release Publihsing

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-runtime-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: chmod +x gradlew
      - run: ./gradlew clean --scan

      - name: previewPublication
        run: ./gradlew previewPublication --no-parallel --info  --scan
        env:
          PUBLICATION_CREDENTIALS: ${{ secrets.PUBLICATION_CREDENTIALS }}

      - run: ./gradlew build --scan # do not split into assemble and check. cache bugs.

      - name: publishMingwX64PublicationToMavenRepository
        run: ./gradlew publishMingwX64PublicationToMavenRepository --no-parallel --info  --scan
        env:
          PUBLICATION_CREDENTIALS: ${{ secrets.PUBLICATION_CREDENTIALS }}

  publish-others-on-macos:
    runs-on: macos-11
    needs:
      - publish-runtime-on-windows
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.1'
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: chmod +x gradlew
      - run: ./gradlew clean --scan

      - name: previewPublication
        run: ./gradlew previewPublication --no-parallel --info  --scan
        env:
          PUBLICATION_CREDENTIALS: ${{ secrets.PUBLICATION_CREDENTIALS }}

      - run: ./gradlew build --scan # do not split into assemble and check. cache bugs.

      - name: publish
        run: ./gradlew publish
          -Dsigner.workdir=/tmp/gpg
          --no-parallel
          --info --scan
        env:
          PUBLICATION_CREDENTIALS: ${{ secrets.PUBLICATION_CREDENTIALS }}

      - name: Publish Gradle plugin
        run: >
          ./gradlew
          publishPlugins --scan
          -Dgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}
          -Dgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}

      - name: Gradle closeRepository
        run: >
          ./gradlew
          :closeRepository --info --scan
          -Dsonatype_key=${{ secrets.SONATYPE_USER }}
          -Dsonatype_password=${{ secrets.SONATYPE_KEY }}
