name: Release Publihsing

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    needs: [ check_duplicate_workflows ]
    if: ${{ needs.check_duplicate_workflows.outputs.should_skip != 'true' }}
    strategy:
      matrix:
        java: [ '8', '11', '15' ]
        platform: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Cache Gradle packages
        uses: actions/cache@v2.1.5
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle

      - run: chmod +x gradlew
      - run: ./gradlew clean --scan
      - run: ./gradlew build --scan

  publish-runtime-on-windows:
    runs-on: windows-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: chmod +x gradlew
      - run: ./gradlew clean --scan
      - run: ./gradlew build --scan # do not split into assemble and check. cache bugs.

      - name: Keys setup
        shell: bash
        run: |
          mkdir keys
          echo "$GPG_PUBLIC_" > keys/keys.pub
          echo "$GPG_PRIVATE" > keys/keys.pri
        env:
          GPG_PRIVATE: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PUBLIC_: ${{ secrets.GPG_PUBLIC_KEY }}

      - name: publishMingwX64PublicationToMavenRepository
        run: ./gradlew publishMingwX64PublicationToMavenRepository --info  --scan
        env:
          GPG_PRIVATE: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PUBLIC_: ${{ secrets.GPG_PUBLIC_KEY }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}

      - name: Gradle closeAndReleaseRepository
        run: >
          ./gradlew
          :closeAndReleaseRepository --info --scan
          -Dsonatype_key=${{ secrets.SONATYPE_USER }}
          -Dsonatype_password=${{ secrets.SONATYPE_KEY }}

  publish-others-on-macos:
    runs-on: macos-latest
    needs:
      - publish-runtime-on-windows
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: chmod +x gradlew
      - run: ./gradlew clean --scan
      - run: ./gradlew build --scan # do not split into assemble and check. cache bugs.
      - name: Keys setup
        shell: bash
        run: |
          mkdir keys
          echo "$GPG_PUBLIC_" > keys/keys.pub
          echo "$GPG_PRIVATE" > keys/keys.pri
        env:
          GPG_PRIVATE: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PUBLIC_: ${{ secrets.GPG_PUBLIC_KEY }}

      - name: publish
        run: ./gradlew publish
          -Dsigner.workdir=/tmp/gpg
          --info --scan
        env:
          GPG_PRIVATE: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PUBLIC_: ${{ secrets.GPG_PUBLIC_KEY }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}

      - name: Gradle closeAndReleaseRepository
        run: >
          ./gradlew
          :closeAndReleaseRepository --info --scan
          -Dsonatype_key=${{ secrets.SONATYPE_USER }}
          -Dsonatype_password=${{ secrets.SONATYPE_KEY }}

      - name: Publish Gradle plugin
        run: >
          ./gradlew
          publishPlugins --scan
          -Dgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}
          -Dgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
